/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2022-07-18 04:25:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LoginPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write(".main{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background: linear-gradient(to top, rgba(0,0,0,0.5)50%,rgba(0,0,0,0.5)50%), url(1.jpg);\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("}\r\n");
      out.write(".navbar{\r\n");
      out.write("    width: 1200px;\r\n");
      out.write("    height: 75px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("}\r\n");
      out.write(".icon{\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    height: 70px;\r\n");
      out.write("}\r\n");
      out.write(".logo{\r\n");
      out.write("    color: #ff7200;\r\n");
      out.write("    font-size: 35px;\r\n");
      out.write("    font-family: Arial;\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    padding-top: 10px;\r\n");
      out.write("    margin-top: 5px\r\n");
      out.write("}\r\n");
      out.write(".menu{\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    height: 70px;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("    float: left;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("ul li{\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin-left: 62px;\r\n");
      out.write("    margin-top: 27px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("ul li a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-family: Arial;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    transition: 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("ul li a:hover{\r\n");
      out.write("    color: #ff7200;\r\n");
      out.write("}\r\n");
      out.write(".search{\r\n");
      out.write("    width: 330px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-left: 270px;\r\n");
      out.write("}\r\n");
      out.write(".srch{\r\n");
      out.write("    font-family: 'Times New Roman';\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: 1px solid #ff7200;\r\n");
      out.write("    margin-top: 13px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border-right: none;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-bottom-left-radius: 5px;\r\n");
      out.write("    border-top-left-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write(".btn{\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    background: #ff7200;\r\n");
      out.write("    border: 2px solid #ff7200;\r\n");
      out.write("    margin-top: 13px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    border-bottom-right-radius: 5px;\r\n");
      out.write("    border-bottom-right-radius: 5px;\r\n");
      out.write("    transition: 0.2s ease;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".btn:hover{\r\n");
      out.write("    color: #000;\r\n");
      out.write("}\r\n");
      out.write(".btn:focus{\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write(".srch:focus{\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write(".content{\r\n");
      out.write("    width: 1200px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".content .par{\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    padding-bottom: 20px;\r\n");
      out.write("    font-family: Arial;\r\n");
      out.write("    letter-spacing: 1.2px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("}\r\n");
      out.write(".content h1{\r\n");
      out.write("    font-family: 'Times New Roman';\r\n");
      out.write("    font-size: 50px;\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    margin-top: 9%;\r\n");
      out.write("    letter-spacing: 2px;\r\n");
      out.write("}\r\n");
      out.write(".content .cn{\r\n");
      out.write("    width: 160px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    background: #ff7200;\r\n");
      out.write("    border: none;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    margin-left: 20px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: .4s ease;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".content .cn a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    transition: .3s ease;\r\n");
      out.write("}\r\n");
      out.write(".cn:hover{\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".content span{\r\n");
      out.write("    color: #ff7200;\r\n");
      out.write("    font-size: 65px\r\n");
      out.write("}\r\n");
      out.write(".form{\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    height: 380px;\r\n");
      out.write("    background: linear-gradient(to top, rgba(0,0,0,0.8)50%,rgba(0,0,0,0.8)50%);\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: -20px;\r\n");
      out.write("    left: 870px;\r\n");
      out.write("    transform: translate(0%,-5%);\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    padding: 25px;\r\n");
      out.write("}\r\n");
      out.write(".form h2{\r\n");
      out.write("    width: 220px;\r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #ff7200;\r\n");
      out.write("    font-size: 22px;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    margin: 2px;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("}\r\n");
      out.write(".form input{\r\n");
      out.write("    width: 240px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border-bottom: 1px solid #ff7200;\r\n");
      out.write("    border-top: none;\r\n");
      out.write("    border-right: none;\r\n");
      out.write("    border-left: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".form input:focus{\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("::placeholder{\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-family: Arial;\r\n");
      out.write("}\r\n");
      out.write(".btnn{\r\n");
      out.write("    width: 240px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    background: #ff7200;\r\n");
      out.write("    border: none;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    transition: 0.4s ease;\r\n");
      out.write("}\r\n");
      out.write(".btnn:hover{\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #ff7200;\r\n");
      out.write("}\r\n");
      out.write(".btnn a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".form .link{\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".form .link a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #ff7200;\r\n");
      out.write("}\r\n");
      out.write(".liw{\r\n");
      out.write("    padding-top: 15px;\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".icons a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".icons ion-icon{\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    padding-left: 14px;\r\n");
      out.write("    padding-top: 5px;\r\n");
      out.write("    transition: 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".icons ion-icon:hover{\r\n");
      out.write("    color: #ff7200;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"main\">\r\n");
      out.write("        <div class=\"navbar\">\r\n");
      out.write("            <div class=\"icon\">\r\n");
      out.write("                <h2 class=\"logo\">Custom Code Snippet</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"menu\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"\"></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"search\">\r\n");
      out.write("                <a href=\"RegisterPage.jsp\"> <button class=\"btn\">Sign Up</button></a>  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("           <h1>Coding With  <br><span>Family</span> <br>Infinite <span>Computer</span> Solutions</h1>\r\n");
      out.write("                <p class=\"par\"><h1><span>Welcome</span></h1> <h2>to my Family Infinite Computer Solutions. Make sure <br>\r\n");
      out.write("                that if you are new User Please Sign Up and if after Sign Up make sure Log In before accessing the Challenges.</h2>\r\n");
      out.write("                <h1 class=\"h1\">Please Login In</h1>\r\n");
      out.write("                <style>\r\n");
      out.write("                .h1{\r\n");
      out.write("                color:black;\r\n");
      out.write("                }\r\n");
      out.write("                </style>\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("             <button class=\"cn\"><a href=\"https://github.com/Sunil-731820\">JOIN US</a></button>\r\n");
      out.write("			<form method=\"get\" action=\"LoginPage.jsp\">\r\n");
      out.write("                <div class=\"form\">\r\n");
      out.write("                    <h2>Login Here </h2>\r\n");
      out.write("                    <input type=\"email\" name=\"userName\" placeholder=\"Enter Email \" >\r\n");
      out.write("                    <input type=\"password\" name=\"passCode\" placeholder=\"Enter Password \" >\r\n");
      out.write("                   <input  type=\"submit\" value=\"Login\">\r\n");
      out.write("                   \r\n");
      out.write("			</form>\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("					\r\n");
      out.write("                    <p class=\"link\">Don't have an account<br>\r\n");
      out.write("                    <a href=\"RegisterPage.jsp\">Sign up </a></a></p>\r\n");
      out.write("                    <p class=\"liw\">Log in with</p>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"icons\">\r\n");
      out.write("                        <a href=\"facebook.com\"><ion-icon name=\"logo-facebook\"></ion-icon></a>\r\n");
      out.write("                        <a href=\"#\"><ion-icon name=\"logo-instagram\"></ion-icon></a>\r\n");
      out.write("                        <a href=\"#\"><ion-icon name=\"logo-twitter\"></ion-icon></a>\r\n");
      out.write("                        <a href=\"#\"><ion-icon name=\"logo-google\"></ion-icon></a>\r\n");
      out.write("                        <a href=\"#\"><ion-icon name=\"logo-skype\"></ion-icon></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"https://unpkg.com/ionicons@5.4.0/dist/ionicons.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
