/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2022-07-13 19:43:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.java.jsp.DatabaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public final class AdminHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.java.jsp.DatabaseConnection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>Admin Home</title>\r\n");
      out.write("        <link rel=\"stylesheet\"\r\n");
      out.write("              href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\"\r\n");
      out.write("              href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("        <script\r\n");
      out.write("        src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("        <script\r\n");
      out.write("        src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("        <script\r\n");
      out.write("        src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("            rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("        <script\r\n");
      out.write("        src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script\r\n");
      out.write("        src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            body {\r\n");
      out.write("                background-image: url(\"img/Medical.jpg\");\r\n");
      out.write("                background-color: #cccccc;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("            }\r\n");
      out.write("            body.modal-open {\r\n");
      out.write("                padding-right: 0 !important;\r\n");
      out.write("            }\r\n");
      out.write("            #sidebar {\r\n");
      out.write("                padding-left: 0;\r\n");
      out.write("            }\r\n");
      out.write("            /*\r\n");
      out.write("         * Off Canvas at medium breakpoint\r\n");
      out.write("         * --------------------------------------------------\r\n");
      out.write("         */\r\n");
      out.write("            @media screen and (max-width: 48em) {\r\n");
      out.write("                .row-offcanvas {\r\n");
      out.write("                    position: relative;\r\n");
      out.write("                    -webkit-transition: all 0.25s ease-out;\r\n");
      out.write("                    -moz-transition: all 0.25s ease-out;\r\n");
      out.write("                    transition: all 0.25s ease-out;\r\n");
      out.write("                }\r\n");
      out.write("                .row-offcanvas-left .sidebar-offcanvas {\r\n");
      out.write("                    left: -33%;\r\n");
      out.write("                }\r\n");
      out.write("                .row-offcanvas-left.active {\r\n");
      out.write("                    left: 33%;\r\n");
      out.write("                    margin-left: -6px;\r\n");
      out.write("                }\r\n");
      out.write("                .sidebar-offcanvas {\r\n");
      out.write("                    position: absolute;\r\n");
      out.write("                    top: 0;\r\n");
      out.write("                    width: 33%;\r\n");
      out.write("                    height: 100%;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            /*\r\n");
      out.write("         * Off Canvas wider at sm breakpoint\r\n");
      out.write("         * --------------------------------------------------\r\n");
      out.write("         */\r\n");
      out.write("            @media screen and (max-width: 34em) {\r\n");
      out.write("                .row-offcanvas-left .sidebar-offcanvas {\r\n");
      out.write("                    left: -45%;\r\n");
      out.write("                }\r\n");
      out.write("                .row-offcanvas-left.active {\r\n");
      out.write("                    left: 45%;\r\n");
      out.write("                    margin-left: -6px;\r\n");
      out.write("                }\r\n");
      out.write("                .sidebar-offcanvas {\r\n");
      out.write("                    width: 45%;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            .card {\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("            }\r\n");
      out.write("            .card-block .rotate {\r\n");
      out.write("                z-index: 8;\r\n");
      out.write("                float: right;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("            }\r\n");
      out.write("            .card-block .rotate i {\r\n");
      out.write("                color: rgba(20, 20, 20, 0.15);\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                left: auto;\r\n");
      out.write("                right: -10px;\r\n");
      out.write("                bottom: 0;\r\n");
      out.write("                display: block;\r\n");
      out.write("                -webkit-transform: rotate(-44deg);\r\n");
      out.write("                -moz-transform: rotate(-44deg);\r\n");
      out.write("                -o-transform: rotate(-44deg);\r\n");
      out.write("                -ms-transform: rotate(-44deg);\r\n");
      out.write("                transform: rotate(-44deg);\r\n");
      out.write("            }\r\n");
      out.write("            a{\r\n");
      out.write("                color: white;\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        ");

            Connection con = null;
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("            <a href=\"#\" class=\"navbar-brand\"> <img src=\"img/2855.jpeg\"\r\n");
      out.write("                                                   height=\"30\" width=\"100\" alt=\"HospitalManagementSystem\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                <h3>\r\n");
      out.write("                    <b>Welcome Health Care </b>\r\n");
      out.write("                </h3>\r\n");
      out.write("                <ul class=\"navbar-nav ml-auto\" style=\"margin-right: 70px;\">\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"nav-item active\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"HomePage.jsp\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            PATIENT\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"addpatient.jsp\">Add Patient</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"adminPatientList.jsp\">Patient List</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            DOCTOR\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"addDoctor.jsp\">Add Doctor</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"adminDoctorList.jsp\">View Doctor</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            RECEPTIONIST\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"addRecp.jsp\">Add Receptionist</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"adminRecpList.jsp\">View Receptionist</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            WORKER\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"addWorker.jsp\">Add Worker</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"adminWorkerList.jsp\">View Worker</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        ");

            try {
                con = DatabaseConnection.initializeDatabase();
                Statement st = (Statement) con.createStatement();
                String query = "select count(*) from patient";
                ResultSet rs = st.executeQuery(query);
                while (rs.next()) {
                    int patient = rs.getInt(1);
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row mb-3\">\r\n");
      out.write("            <div class=\"col-xl-3 col-lg-6\" style=\"margin-top: 20px; \">\r\n");
      out.write("                <div class=\"card card-inverse card-success\">\r\n");
      out.write("                    <div class=\"card-block bg-success\">\r\n");
      out.write("                        <div class=\"rotate\">\r\n");
      out.write("                            <i class=\"fa fa-user fa-5x\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h6 class=\"text-uppercase\" style=\"text-align: center; \"><a href=\"adminPatientList.jsp\">Patient</a></h6>\r\n");
      out.write("                        <h1 class=\"display-1\" style=\"text-align: center\">");
      out.print( patient);
      out.write("</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                    }
                    con.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            
      out.write("\r\n");
      out.write("            ");

                try {
                    con = DatabaseConnection.initializeDatabase();
                    Statement st = (Statement) con.createStatement();
                    String query = "select count(*) from doctor";
                    ResultSet rs = st.executeQuery(query);
                    while (rs.next()) {
                        int doctor = rs.getInt(1);
            
      out.write("\r\n");
      out.write("            <div class=\"col-xl-3 col-lg-6\" style=\"margin-top: 20px;\">\r\n");
      out.write("                <div class=\"card card-inverse card-danger\">\r\n");
      out.write("                    <div class=\"card-block bg-danger\">\r\n");
      out.write("                        <div class=\"rotate\">\r\n");
      out.write("                            <i class=\"fa fa-user fa-5x\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h6 class=\"text-uppercase\" style=\"text-align: center\"><a href=\"adminDoctorList.jsp\">Doctor</a></h6>\r\n");
      out.write("                        <h1 class=\"display-1\" style=\"text-align: center\">");
      out.print( doctor);
      out.write("</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                    }
                    con.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            
      out.write("\r\n");
      out.write("            ");

                try {
                    con = DatabaseConnection.initializeDatabase();
                    Statement st = (Statement) con.createStatement();
                    String query = "select count(*) from recp";
                    ResultSet rs = st.executeQuery(query);
                    while (rs.next()) {
                        int recp = rs.getInt(1);
            
      out.write("\r\n");
      out.write("            <div class=\"col-xl-3 col-lg-6\" style=\"margin-top: 20px;\">\r\n");
      out.write("                <div class=\"card card-inverse card-info\">\r\n");
      out.write("                    <div class=\"card-block bg-info\">\r\n");
      out.write("                        <div class=\"rotate\">\r\n");
      out.write("                            <i class=\"fa fa-user fa-5x\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h6 class=\"text-uppercase\" style=\"text-align: center\"><a href=\"adminRecpList.jsp\">Receptionist</a></h6>\r\n");
      out.write("                        <h1 class=\"display-1\" style=\"text-align: center\">");
      out.print( recp);
      out.write("</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                    }
                    con.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            
      out.write("\r\n");
      out.write("            ");

                try {
                    con = DatabaseConnection.initializeDatabase();
                    Statement st = (Statement) con.createStatement();
                    String query = "select count(*) from worker";
                    ResultSet rs = st.executeQuery(query);
                    while (rs.next()) {
                        int worker = rs.getInt(1);
            
      out.write("\r\n");
      out.write("            <div class=\"col-xl-3 col-lg-6\" style=\"margin-top: 20px;\">\r\n");
      out.write("                <div class=\"card card-inverse card-warning\">\r\n");
      out.write("                    <div class=\"card-block bg-warning\">\r\n");
      out.write("                        <div class=\"rotate\">\r\n");
      out.write("                            <i class=\"fa fa-user fa-5x\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h6 class=\"text-uppercase\" style=\"text-align: center\"><a href=\"adminWorkerList.jsp\">Worker</a></h6>\r\n");
      out.write("                        <h1 class=\"display-1\" style=\"text-align: center\">");
      out.print( worker);
      out.write("</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

                }
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
